frame_id: map
default_step: 0.45
default_yaw: 0.0
rooms:
  living_room:
    display_name: living_room
    marker_id: 2
    step: 0.45
    polygon:
      - {x: 0.85, y: 0.25}
      - {x: 3.05, y: 0.25}
      - {x: 3.05, y: 1.35}
      - {x: 0.85, y: 1.35}
  kitchen:
    display_name: kitchen
    marker_id: 5
    step: 0.25
    polygon:
      - {x: 0.80, y: -1.20}
      - {x: 1.95, y: -1.20}
      - {x: 1.95, y: -0.75}
      - {x: 0.80, y: -0.75}
  bedroom:
    display_name: bedroom
    marker_id: 4
    step: 0.30
    polygon:
      - {x: 3.85, y: 0.60}
      - {x: 4.95, y: 0.60}
      - {x: 4.95, y: 1.05}
      - {x: 3.85, y: 1.05}
  study:
    display_name: study
    marker_id: 3
    step: 0.30
    polygon:
      - {x: 2.35, y: -0.20}
      - {x: 3.05, y: -0.20}
      - {x: 3.05, y: 0.25}
      - {x: 2.35, y: 0.25}
